<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]> <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]> <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>trans-AT PKS-derived Polyketide Prediction Tool</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

    <link rel="stylesheet" href="css/normalize.css">
    <link rel="stylesheet" href="css/main.css">
    <script src="js/vendor/modernizr-2.6.2.min.js"></script>

    <script type="text/javascript">
        function submitExample() {
            $("#sequenceInput").val(">bacillaene\n" +
                "MKSDMKASGLLKPSVSYGKSLRLSADQPMTIPEVLHKTAAAAGDQKGITYIQPDGTKVYQ\n" +
                "TYSSLKKIALSIVKGLRQSGVKAQDEVILQLSDNSQLIPAFWGCVFLGAIPVPLAAAPAY\n" +
                "TEMNSGTQKLKDAWTLLNQPYVITSRDVLPEMTEWAEEQGLSGFCALAAEDLSAHEMDTD\n" +
                "CHHPRPEDLAMLLLTSGSTGTPKAVMLSHENIVCMVKGNIQMQGYTSEDVTFNWMPFDHV\n" +
                "GGIGMLHLRDVYLGCEEINIPSESILMDPLKWLDLIDHYRASVTWAPNFAFGLLADFAEE\n" +
                "IQTRKWDLSSMRYMLNGGEAAVAKVGRRIMELLEPHGLPANAIRPAWGMSETSSGVIFSD\n" +
                "EFTLENTNDDDRFVEIGLPIPGFNMRITDDRNQVVEEGEIGRFQVSGLTVTSGYYERPDL\n" +
                "NESVFTEDGWFETGDLGFLREGRLTITGRTKDAIIINGVNYYSHAIESAVEELPEIETSY\n" +
                "TAACAVRPNQSTTDELAIFFVTSVPLDENRMTKLLHHIHQHVTQRIGVTPDYLLPVAKED\n" +
                "IPKTAIGKIQRTQLKHSFEQGQFDSLHNNRQEGGNSDTASAEKEIERDFIRFLKEELSIA\n" +
                "EELVDPNTPFQSLGVNSIKMMKLARSIEKTYHIRLTARELHKNPTIGALAAYTAEKAANM\n" +
                "SAEHHPQKAEPPAERERRQTAPALSEVQKGLWTLQKMSPETTAYHVSLCFRFTSGIDKEK\n" +
                "LKQAFQLVLKQHPMLKSAVNETDGGFYFIEAADPFVFSEEDISDVNETQISALIRKKVKE\n" +
                "PFVKEGGPLLRVQLLSKSAEEHYLLTVIHHIVFDGISSITFIHSLLDHYQALLEGKEEFT\n" +
                "AAAPGIHPDFAAWEKRYLAGDESKAARAYWMKQLEGDLPDLQLPPMRTDSSVPEFTEDTL\n" +
                "TRRLPERLLNNITAFAASRSIHLSTVMLSCYMVLLSKYTDKEDIVTGMPAMVRPEERFDG\n" +
                "VVGHFLNMLPIRSRAGRKETFADFVQKVQDAVLDGLDHSFYPFPKMVRDVHAKPLQNGSP\n" +
                "VFSNAFFYQNFLQHSSYQSMLDEYKEFSCEFVKDIHQEGEYDLVFEMWEEASGMDLTIKY\n" +
                "STELFDEAGAARLFSQFVQAAEALTANPDTPLENVSLMTKREEHMILKTWNETSREYPDA\n" +
                "CFHELFERQAAETPDACAVVYEQQQLTYRELDEKSTKLALYLQAHGAGPDDLIGIYTDRS\n" +
                "LHMAVGLLGILKAGGAYVPLDPSYPADRLEYMIADSRISMCLTTADLEHSLNWGGVQTTA\n" +
                "IDRDWSHIESTAAERTSLKRLVTPDDLAYVIYTSGSTGKPKGVMIPHRALTNFLISMANE\n" +
                "PGLSSEDKLLAVTTYCFDIAALELYLPLIKGAECNICKTEVTKDARKLKELIQEYKPTIM\n" +
                "QATPFTWKMLFHSGWSNEENVKILCGGEALSEQLKQQFLDTKSEAWNMFGPTETTIWSAV\n" +
                "QRITENESALTIGRPIANTRVYIMDSGLNPVLEGVPGELCIAGDGLARGYFNKPELTDKA\n" +
                "FVSHRLELGSKLYKTGDMARFLPGGRIEYMGRMDTQVKIRGYRIEPGDIESRLNAHPAVQ\n" +
                "ESVVVVNNHSGNEKLCAFYIRKNGEPLPSAKELRKHMKQALPAYMAPASFVRLEELPLTP\n" +
                "NGKVDRKLLAARDLTEKQPDTQTFSSSHIQQAVLAIWQDVLKSKDIELDDRFFDAGGDSL\n" +
                "LAVTVTDRMTQELDCEFSVTELFEYATVKDISRYITEQKPKEAFLAPVPQKKVNAEDREH\n" +
                "PAGEFPDYYEDSLAVIGISCEFPGAKDHYEFWNNIKEGKESITFFSKEELRRSGISEELA\n" +
                "DHPGFVPAKSVLEGKEMFDPGFFGFSPKDAEYMDPQLRMLLLHSWKAIEDAGYISKEIPE\n" +
                "TSVYMSASTNSYRSLLPEETTAQLETPDGYVSWVLAQSGTIPTMISHKLGLKGPSYFVHA\n" +
                "NCSSSLIGLHSAFQSLQSGEAKYALVGGATLHTESSAGYVHQPGLNFSSDGHIKAFDADA\n" +
                "DGMIGGEGAGAVLLKKASDAVKDGDHIYALLRGIGVNNDGADKVGFYAPSVKGQAEVIQK\n" +
                "VIDQTGIHPETIAYVEAHGTGTKLGDPIELSALQSVYGRYTDKKQYCGIGSVKTNLGHLD\n" +
                "TAAGMAGCIKVVMSLYHQEIAPSINYKEPNPNLHLEDSPFFVAEEKKELTRENRAHRMAL\n" +
                "SSFGLGGTNTHAIFEQYPDASEAADAAGPFIIPLSARKKDRLKEYAKQLLAFLERKTDTD\n" +
                "LADLAYTFQVGREAMEERAAFITSGTAELKRQLADFINDKPAVTGCFRGEKQQAKDIAWL\n" +
                "SDDDDSAELIEKWLAKGKGPKLCEMWSKGVAINWHKLYKDKHPKRISLPVYPFAKEPYWP\n" +
                "KKAEKNTSAAHTGVSVLHPLVQQNTSDLAVQRFSSRFTGSEFFLKDHVVREKAVLPGAAY\n" +
                "LEMSYEAVKRALGGLLKDQDRITLHHTIWMKPIVVHEQERQVHIALFPEEDGIISYDIYS\n" +
                "VNADGEEVLHSQGRAEIIKAEREPEADLSAIQNRCTADILDPAAFYREGRSRGMFHGKAF\n" +
                "QGIKSAFIGEKEVLSDIQLPDSVSHTNGQFTLHPSIIDSAIQTATICIMQEFSGQKLILP\n" +
                "FALEYLEVIKACTPTMRAHARFSDGYQTGNSVQKADIDLFDETGALCVKVRGFSTRVLEG\n" +
                "DAESAQPPSGSEKVLFAPVWKEAAASEKASVRADEHLIILCEDACRIKDETASGLKDAEL\n" +
                "LIAEGEGETAAERFQSYAQTIAEHIRRIISEKRQGRILIQTVISADGSQQLFAGLTGLLK\n" +
                "TAELEYGKLDCQLIEMESIGEMPAVAQKLKNDSHQPHDKHIRYKGEKRYVKAWEEMHPAG\n" +
                "GGIVWKDEGVYLITGGAGSLGLMVAKEIAGRVKHPKIILTGRSNLTEAKQRELAMLQHSG\n" +
                "ANVVYKKLNAADRRENEAMIKEITAEFGKLNGIIHAAGVIQDRFLLQKTKEEFREVLDPK\n" +
                "VIGTAYLDEASKDCNLDFFVLFSSVSGVLGNVGQADYAAGNAFMDAYAAYRQSLTENGLR\n" +
                "HGKTVAFNWTLWKDGGMQAGDETERMMKKAFGMVPLQKASGLAAFYEGMAQEKPQLLAAE\n" +
                "GHAAKLKQSFLSVSETEKPQVKKIEPVSAVSGDKWHGALIRLVSSILKVGQDEIDIDTEL\n" +
                "SEYGFDSVSFTVFTNQLNEAYQLKLAPTIFFEHGTIRSLADYLTDEAEAGLPSQPEEKHD\n" +
                "ADKSLQTLHTALTAMVSGILKVDREDIETDTELSEYGFDSVSFTVFTNQLNEAYQLELAP\n" +
                "TIFFEHGTISGLAGYLAKEHPGRFGEKKKESPKKEQPKAQKPKMQRKKRFATVMNASAAT\n" +
                "QEPRRFDPVAIVGISGRFPGAKDIEEFWRNLKEGKDSITTIPKERWDWQAFDGDPNLEGN\n" +
                "KTNIKWGGFIDGIAEFDPLFFGISPREAQYLDPQQRLLLTYAWRAIEDAGCKPESLSGTN\n" +
                "TGVFIGTGNTGYKDLFTRAGLAPEGHAATGSMIPSIGPNRLSYLLNLHGPSEPIETACSS\n" +
                "SLVAIHRAVSAIENGECDMAIAGGINTILTEEAHISYSKAGMLSKDGKCKTFSKDANGYV\n" +
                "RGEGAGILMLKKLSDAERDGNPIYGVIRGTAENHGGRANTLTSPNPKLQADLLVKAYRKA\n" +
                "GVDPSTVTYIEAHGTGTELGDPIEINGLKAAFHELAKTNQEPEVSGHRCGIGSVKSNIGH\n" +
                "LELAAGVSGVMKVLLQMKHKTLVKSLHCETINPYIQLDDSPFYIVRENQEWTAAKDRNGN\n" +
                "AIPRRAGVSSFGIGGVNAHIVIEEYVPKAAAQPEHSPENPAIILLSAKSKEKLFEQAQQL\n" +
                "QKAIRQTPYTDQDLAGVAYTLQTGRDEMEERLAILAATMAELETKLEAFTKNEKNIAGLY\n" +
                "TGQSHRNKDTFALFTADEDMDIVIDAWIKKGKFAKLAEVWVKGGVFNWNRLYEKGTPRLL\n" +
                "SLPSYPFAKDTYWVPENPDKNKVHTEERMKRILTKQWELSPLELREPCARSVAILTGGDT\n" +
                "INLAEEIAAHMPNHRIITASDLSGEYDWQAFDGVIDLLGAAKEDSQDMAGIKWLQQLIEH\n" +
                "GHKEGMTLLCVTKDLESLNKEANQTTGAKRAGLYRMLAYEYGHLSSRHLDLEGALSDDKL\n" +
                "AKQIADEFHARTDDAEVCRRDGLRYRAVLSGAENMNMKGERIDFPDNHVLLITGGTRGIG\n" +
                "LLCARHFAEHYGVKKLVLTGRETLPPRSEWTGGLNGVPASVKAKIEAVLDLESKGVQVKV\n" +
                "LSVPLADEAGLRQELSQIKQTLGPIGGVIHCAGVTDKETLAFIRKTDEDIQRVLEPKVDG\n" +
                "LQALYSVLSEEPLKFFVLFSSVSAAIPALSAGQADYAMANAYMDYFANSYKEQLPIVSIQ\n" +
                "WPNWKETGMGEVTNKAYKESGLYSITNAEGLQLLDGILLESARGPVLPAVLNPKLWKPER\n" +
                "FLRRSRQDQPMSPAMVKPAEKTAYTAENNTQLTRKTEEWLKELFSEELRIDQDQLETDVL\n" +
                "FQDYGVDSIILAQLLQRINRNLSASLDPSILYEYPTIQSFANWLLEGYTEVLSERFDLAA\n" +
                "EPVKKNPAEPVIETQAVKVQEEPAGKQIHREDIAVVGMSCRFPGAASLEAYWSLLAEGRS\n" +
                "AIRPVPAERWGLKTPYYAGMLDGIHQFDPDFFLLAEEDVKAMDPQALAALEECLNLWYHA\n" +
                "GYTPDEIKGEAIGVYLGGRSRHRPGEDKLLDAKNPIVALGQNYLAANLSQYFDMRGPSVV\n" +
                "LDTACSSALVGMNMAVQALVSGEIKAAVVGGVSLFESEETHKLFEQRGILSKAQSFHVFD\n" +
                "ERADGVVLGEGVGMVLLKTVSQAIEDGDSIYAVVKAASVNNDGRTAGPATPSLEAQKSVM\n" +
                "KTALEKSGKQPEDITHIEANGSGTVVTDLLELKAIQSVYRSKDAGPLGIGSVKPNIGHPL\n" +
                "CAEGIASFIKVVLMLKEKSFIPFLSGEHENTHFDREKANIQFSRTLADWPSPIPAAGINC\n" +
                "FADGGTNAHVIVEAWQEDEGRRIKRHPLTPPALNKRLISPDSKEETNEKAAANIWDTYEV\n" +
                "EVMKWRFNVKNFNKQITLSLKNPFILHHDVYGQKVLPGLAYIDMFYQIFKERGYSYDGLQ\n" +
                "LRHLSIYQPLIAKEDSAVKLTVECTKVKEGRWKLTAKGAEVSGGRVQPEERIYVKAEMHE\n" +
                "TAPAIFSETLDLDSVKREAERTIDLNELYAQCRSQELVHSGYMKAEGEVFEERDGVTFDV\n" +
                "SLGKDAMGQAGGFLFHPTLLDGSGVGANLLISSLLNGEKRLFLPLFYESFTASEPLQAGC\n" +
                "ITRIKRSSLRQEKELIYITLEFFNASGRKVAELKDFTSKLVRDAELINTERKTAEKSPEK\n" +
                "AGLPEVAASLEGGHPHEEAERYVMNLMAEKIGKPLEQIDSQVGYYEMGLTSSGLLDVVET\n" +
                "ISEKIGETLSPTLLFEYTTAAELAAFLTEQYGSHFSASPAKMEKQVETQTERRRKSSVPQ\n" +
                "DEDIAIIGMAGRYPQAENIHEFWENLKEGKNCVTEIPESRWDWRRFENVKSPSGKSISKW\n" +
                "GGFIDDPDCFDPQFFRITPREAETMDPQERLFLQTCWETIEDAGYTPKSLAEARGRNKRQ\n" +
                "RVGVFAGVMHKDYTLVGAEASSEDHVFPLSLNYAQIANRVSYFCNFHGPSMAVDTVCSSS\n" +
                "LTAVHLAAESIRRGECESAVAGGVNLSLHPNKYLTYGLWDMFSTDGVCHTFGKDGDGYVP\n" +
                "AEGIGAVLLKPLREAVKDGDRIYAVIKGSAVNHVGTVSGISVPSPVAQADLIEECLDKAG\n" +
                "IDPRTVSYIEAHGTGTSLGDPIEVQGLVKAFRQYTQDKQFCSIGSVKSNIGHAESAAGIS\n" +
                "GLSKVALQLHHKTLVPSLHSEELNPYLDFEQSPFYVQHHTEAWQQPSVTENGNETVYPRR\n" +
                "AGISSFGATGSNVHLILEEFIPEESHGTNAEPAEEQTFIFPVSARNEERLKEYVAKLSAF\n" +
                "IHPGLPLEDAAYTLQIGREQMEERVVFTAQNMTQLKERLEGFLAGKTVSGCWRNRADKSK\n" +
                "QAELAPDLIHKWLSSGSLEMIAEKWAGGGTMDWKLLYGENKPNRISLPTYPFEKIRYWVP\n" +
                "KAEKRESLPQKNAGMLHPLLHENVSNMSGVRFRSSFSGGEFFLKDHVVKNERTLPGAAYL\n" +
                "EMVRAAVEHAAETKEEGTVRLKHVVWIRPFTAADESADLYLRLYDEENGEMGFTVYSESA\n" +
                "SSEEEPVLYAQGSAAFVRAGEPAKIEIDKLRESRRLITPDACYQAYKQMGIEYGDAHKAV\n" +
                "TEIYAKDSKVLAKLSLPSSISHTKDQFVLHPSLLDAAFHATIGLMLDRDGTDIRPMLPFA\n" +
                "LEQIDVLKSCKSDMWVSIAYSGESKPEDAVQKLDIDVCDEQGNVCVKMTGYSAREIETDK\n" +
                "TDTLYFEHVWEEKAAVHEEAPIHFKARHVMISDRFTDQMNSIQTDFSCHVLRDQHKSEDE\n" +
                "RFEACALQAFEEVKKILASNSGGRELIQIVVPQEADTQLLCGLTGLLKTAALENPNLTGQ\n" +
                "LIETEPDVKADTLSRYVKECSAHPDDKHIRYENGRRYTAQWQETGLEQFGAEKPWKDKGV\n" +
                "YLITGGAGGLGFLFAREIARHAKDAVLILTGRSLLDNRKKAQLQELSDLGAQAVYKQTDM\n" +
                "TEKQEVQSLTADICRQYGGLNGIIHSAGTIKDNYILKKHKDEIRDVLAPKVSGLVHLDEA\n" +
                "AKDIELDFLILFSSGAGSAGSAGQADYAMANAFMNAFSEKRNRKKARNERYGHTLSICWP\n" +
                "LWKDGGMTVDAETEAMLTKESGMVPMQTENGIQALYRGWAANTSQVMVTEGYAAKIRAFL\n" +
                "KKSADDQPDKGSETEEPVGLTASGENMLAEKTEHFLKQVLSEVTKLPVGKIDAKAPMEDY\n" +
                "GIDSIMIMHLTGRLEKSFGSLSKTLFFEYQNIESLTQYFMKAHRDTLLEVTGMKTEETPA\n" +
                "AKPALSEKAKVKPVFKRNEGKKGFAQVRPDTRENQQLTEREDIAIIGISGRYPQAENLQE\n" +
                "FWKNLSEGTDCITEIPNDRWDHSLYYDADKDKEGKTYGKWGGFLKDVDKFDPQFFSISPR\n" +
                "DAKLMDPQERLFLQCVYETMEDAGYTRKKLTEKSGDLLGANVGVYVGVMYEEYQLYGAEE\n" +
                "QARGKSLALTGNPSSIANRASYVFGFNGPSMALDTMCSSSLTAIHLACQSLRNGECEAAF\n" +
                "AGGVNVSVHPNKYLMLGQNRFLSSKGRCESFGEGGDGYVPGEGVGAVLLKPLSKAKADGD\n" +
                "HIYGLIKGTAVNHDGKTNGYSVPNPNAQAAVIKQALKDAGTDPRAVSYIEAHGTGTSLGD\n" +
                "PIEITGLTKAFSEQTQDKQFCAIGSAKSNIGHCESAAGIAGLTKVLLQMKHKQLAPSLHS\n" +
                "RTLNPNIDFLATPFKVQQTLEEWKRPVINENGVNKELPRTAGLSSFGAGGVNAHIVIEEY\n" +
                "SADEDKETAFAAPHPSMIVLSAKNEQRLQKRAKRLLDALRSGRYREADLSRIAYTLQVGR\n" +
                "EPMEERLGMIVSNLRELEEKLDEFTGGKESIDQLYRGQVKQNKDTMALFTADEDMEKTIE\n" +
                "AWLEKGKAAKVLELWVKGLPLNWDKLYQMGRPQKISLPAYPFAKDRYWIDTSADAAVKRP\n" +
                "AETQSAPIAPAAAPEPVIEVTTLHEETVKEKPSNITLQTLSGAKPKRTVQPASRPAVSAE\n" +
                "KVSAVLTESLADVLYMDADDIDADDTFIDIGMDSITGLEWIKSVNKAYGTSLTVTKVYDY\n" +
                "PTIRQFAAFLQKELGTEPILEEATEPQKTEAVKKPSNIMLQPLNAHKQHVIQAEADILEA\n" +
                "MSETAASAEPEEPIEAVHDELSKALADVLYMERHEVDIDEAFIDLGMDSITGLEWIKAVN\n" +
                "KRYGTDCNVTKVYDYPTIRQFADFLRAQPSVRGRKKQAVPVRPKPLTQQHAPQEKTPAEP\n" +
                "ERLTIQKEPEPVQAKREPKDEIADAIAIVGMSGKYPDAPELKTYWDNLARAKNAIRDIPL\n" +
                "SRWDVNKYYDPALNKKGKVYCRSIGMLDDIEEFDPLFFNISPSEAELMDPQHRIFLQEGF\n" +
                "KAFEDAGYSSKELNGKNCGVYLGIMNNEYGMMLNKHQTGGSATGNSFSIAAARLPYYLNL\n" +
                "KGPAIPIDTACSSSLVGAHLARQALLNHEIDMALVGGVTLYLTPESYISMCEAGMLSPDG\n" +
                "QCKAFDNSANGFVPGEGAGALVLKRLKDAEADQDHIYGVIIGSGINQDGKTNGITAPSAK\n" +
                "SQMDLERQVYEAHNIHPESITYAEMHGTGTKQGDPIELEALSSVFKEKTDRKQFCAIGSV\n" +
                "KSNIGHTSAAAGVASVQKVLLSMKHQQLVPTLHFSTPNEHFDFDDSPLFVNTELKPWETG\n" +
                "GAPRRACVSSFGYSGTNAHLVIEEYQPKDRGSRKPDETNIFVLSAKKAPQVKTYAESVIE\n" +
                "FAKADQNINLSDMAYTLQTGRDAMDYRLAVTAGSREELISRLTDFVNGNTGEGIYEAHIK\n" +
                "TAKKEIKAFETDDDLKQLVRSWFDKKKYAKIAELWAKGLQMDWDRLYQGEKPRRISLPAY\n" +
                "PFAKEPYWLPEPKVIPQETEDRREAVLLEKQWVPCEIDSAGEKSGRTVMILADARTAELA\n" +
                "EETAKHFADSFILPVDSADTAASDWNHIDGAIDLTGCGDEDPSLEGISRLQTLIDTSRRQ\n" +
                "ARPLTLLYVTKGLEPFQQKTIHLAGAAKSGLYRMLQNEYQNVTSRHMDADKDTDQQTLAK\n" +
                "QIADEFSADCTEPEICRRNGQRYRALFREIPSGKRAEHKPAPFPEDHVLFITGGTRGLGL\n" +
                "LCARHFTEKHGVKKVVLTGREPIPPRHKRSAVNTRLKEKIRAIEELEAKGVQVAVISLKL\n" +
                "SDHDAAAAEIETIRRTMGPIGGVIHCAGSVNSVNPAFIRKTAEDIQEVLEPKVAGLQTLS\n" +
                "SLFTNDPLQFFVLFSSVSAVVPALAAGQSDYAMANAYMDYFAAAHQHQYPLVSIQWPNWK\n" +
                "ETGLGEVRTESLKQTGLLGLSNAEGLDLLDRILSENIRPSVLPAIVDRSEWHPDRLLCQE\n" +
                "KKQKETEAVINGKAAEKHSDRELLLDTKAWLVKLFSDELKIAPEELETDEPFQDYGVDSI\n" +
                "ILAQLLQQMNQALKEDLDPSVLYEHPTIDAFAEWLVSNGQPLLAEREEPDTEMLLPAAVQ\n" +
                "TVHTEQKRDAVTEDIAVVGMSCRFPGAESLEQYWDLLRSGRSAIGSVPAERFGYANQYVA\n" +
                "GLIDNMDHFDSEFFFIPENDAKAMDPQALAVLEESLKLWCHAGYSREEIKGIEAGVYIGG\n" +
                "RSQHQPDPEILANTRNPIVAGGQNYLAANVSQFFDLRGPSIVLDTACSSALTGMNMAVQA\n" +
                "LRSGDIKAAVVGGVSLLNTDAAHRMFQERGLLNEKPAFHVFDKRSGGVVLGEGVGMVLLK\n" +
                "TVSQAQKDGDTIHAVIKAAAMNNDGRTAGPSAPNMQAQKDVMQSALFKSGKKPEDISYIE\n" +
                "ANGSGSAVTDLLELKAIQSVYRSGQHVPLGIGSIKPNIGHPLCAEGIASFIKVVLMLKHK\n" +
                "QTVPFLSGDEPMPHFDITKTDFHFHKTAGEWDAARPSAAINCFADGGTNAHVILEAWEEK\n" +
                "DTRMKRKPLPVPSLRRKALVKEPDAPAEKQELPAKKMFWKAFKMREEWEGMISEKINISL\n" +
                "DHPIMKGHKVFGEAVLPGLAYIDLIYQVFQEHGYVYNELELKHVTIYQPLTVSETAAIIL\n" +
                "TIQCSDSGDGKWLISLSGQKQQGDELSDNIQYATAEMVKRDAVTFDETIDFGDVKQSGRS\n" +
                "LNLDDMYNRCLDHDLVHSGMMKSNGRLYETEDGMLAELSCKEGKGFFLFHPALLDASGIG\n" +
                "ASGLLSETNRLHLPLYYESFTAADRLQSECTARIAASGVRQEKELTTMTIEYFSRSGQKV\n" +
                "AELKNITGKAVRFEEDENTAEQNQQAATEPESADEKDIILFLKKLLADKLGQPWETLDVL\n" +
                "AGYYELGLDSSSLLEIVQDISKKTGADLAPTLLFEYTNIKELAAYLKKTVSFECAERAAE\n" +
                "PSRSEAEAPDTPEHHKNTGDIAIIGMAGRYPKAKSVAEFWENLKAGTDCITEVPKSRWDW\n" +
                "KTYKNVTSPSGKTVSKWGGFIDDADCFDPQFFRISPREAETMDPQERLFLETCWETIEDA\n" +
                "GYTPETLGNKGEKQHPIGVFAGVMHKDYSLIGAEQLSETDPFPVSLNYAQIANRVSYYCD\n" +
                "FHGPSIAVDTVCSSSLTAVHLAIESIRRGECEAALAGGVNLSLHPAKYLSYGSVGMHSSD\n" +
                "GRCRTFGEGGDGYVSGEGVGAVLLKPLEKAEQDGDRIYAVIKGSAINHVGKVSGITVPSP\n" +
                "AAQAEVIKACLKKAGISPRTVSYVEAHGTGTSLGDPIEIEGLSKAFSQGTQDQQFCSIGS\n" +
                "VKSNIGHAESAAGISGLTKAALQLHHKTLVKSLHSAELNPYLKFEESPFYVQQQTAPWKQ\n" +
                "PSAEENGKVTHYPRRAGLSSFGASGSNAHIILEEYIQPEQKAPAPENEAAKLIPLSARNK\n" +
                "DRLLAYAEKLARSLSEKTVLSELAYTIQTGREAMEERAVFLVNDIRDLKQKLNDFVKGNE\n" +
                "NIPGLWRGQAELPEMSETAPETDDSIRLAELWAEGKTVDWNKLYGSGKPRKTSVPTYPFA\n" +
                "KERYWIPQQKKQEKSPSGTVLHPLLQENTSDFSQQRFTSLFTGDEFFLSDHVVNGQKILP\n" +
                "GVAYLEMAAEAVKKAAAVTEKDHSVTLRQVVWVRPVMIEDKPKEIHIALYPEDNGEITYE\n" +
                "IYSEAENGEDPVIHSQGEAVITEPGSAQIDIESVKASCNLGIVTAEECYGAFEKIGLDYG\n" +
                "EAYRGVQQLLIGEDRLLARISLPAAVHDKKEQYTLHPSMMDAAFHASVGLLVRSIHDDAD\n" +
                "SHELALPFAMQEVEVFGPCPEHIWSYIRYTEGSKADDNVRKFDIDMCDDAGTVYVRMKGA\n" +
                "SVRALDTSQTAGGETTEAPVGHTMLIPAWEPVALEKAGEAAADKQTAVFGGTDSRHTRIK\n" +
                "EHLPNASYYPIRGTDDITSLTHMLEGQKELEQIIWLAPQAESADSLKEQERNVLHVFKLM\n" +
                "KALLALGYGEKRLDWCIVTANAQPFSDQDSADPSQAAVSGLAGTMAKEYPHWHIRMIDTE\n" +
                "TDGSWPIEEALSLSAGKNGQIWAYRNQQLFERQLIPLDNMPKNGTLYQTGGVYAVIGGAG\n" +
                "YLGEAWSEYMIRRYKARIIWIGRSTLNDSIQAKLDRLSAFGPAPEYVSADAADSASLERA\n" +
                "YQFIKERHTKMNGIIHSAMDLSEQSLNNMKTEEFKSVLRAKADVSVSMAEVFGREPLDFA\n" +
                "LFFSSLVAFIHNVKQSHYAAGCAFSDAFAKELDQTWNCPVKVMNWGYWGNSEAAEDGDFI\n" +
                "QLMDQIGLGLIEPDAAMEALETLMTLPVDQAAFIHTTKPVAVEGMNEREKISVYPPQPLV\n" +
                "FSQQPKVAPPGARLVREAEHQELDDYLYQLLIAQLKEADLLTPQSLKAYEPEHEYFKKWL\n" +
                "NQTIAFLLEHGYLEGNADSYKLSARAENTTAALWQKWEREKEEWLNNADTKAMTVLAETM\n" +
                "LKALPDILREDVPATDIMFPHSSMELVEGIYKHNQVADYFNSALSDTLTAYVKENISKHS\n" +
                "KAEIRILEIGAGTGGTSAGIFEKLRPYQNHIKEYCYTDVSKAFLVHAETEYGKRNPYLTY\n" +
                "KLFNAEAPLAGQDIEPGAFDIVVAANVLHATKDIRQTLRNAKAVLKDNGLLLLNEMAGNS\n" +
                "LFPHITFGLLEGWWLHEDSALRIPGCPGLYPESWKRVLESEGWHSVFFPAEAAHELSHQI\n" +
                "IAAKSNGIVRQKTLKAGAGKRTSPPKAAHAPELQAQTTVQKGDTSLTEKSTEYLKTLIGE\n" +
                "TLKIPPAQIDPKAPLEKYGIDSIVVVQLTNALRNVLDQVSSTLFFEYQTIEALVAHLIKT\n" +
                "KKDAMIKLTGQTPVQEERKASPEPQAVQPAKPLRTDWRRREKRAAKETVRQISVRDVAII\n" +
                "GVSGRYPQAKTAAELWANIKKGKNCIEEIPRERWNWQDYYDEEKGKEGSIYTKWGGFIED\n" +
                "MDKFDPLFFQISPLEAERMDPQERLFLETAYASIEDAGYTPDNLCQSRKIGVFAGAMNKN\n" +
                "YPTGYGYWSIANRVSYLFDFQGPSIAVDTACSSSLTAIHLALESIYSGSSECAIAGGVNI\n" +
                "VTDPIHYMNLSVMNMLSAGDTCKSFGDRADGFVDGEGVGAVVLKPLDRAIADNDHIYGVI\n" +
                "KGSTINSGGKTNGYTVPNPNAQAALIKEAFERANVPARTVSYIEAHGTGTALGDPIEIAG\n" +
                "LTKAFEEDTTDKQFCAIGSAKSNIGHCESAAGIAGLTKILFQLKDRQIAPSLHADQLNPN\n" +
                "IDFAYTPFAVQQELGEWKRPVIGGKELPRRAGLSSFGAGGANAHLVIEEYTADKEPDEMP\n" +
                "ADQPAIIVLSAKNSERLTEKAKQLRDAIREKRYSCSDLMSIAFTLQTGRVPMEERLGFIV\n" +
                "HSLHELEEKLNGFIAGHNSAGLHRDGTEENKRMLAVFSADDDLETIIDAWISKRKYSKLL\n" +
                "ELWVKGLDIDWTKLYGDRPPARISLPAYPFAKERFWHQQPVQSKAAPVNAPADESDPAEQ\n" +
                "FEVMAFREVLKEQALPAAGDKQVKTVISFLSDQKKQQEAISMIKSYDNDIDVIFIAQGDR\n" +
                "YEALSAGRCQVVREDPQSYVNAFADIQKEYGEASAILYLWALEDKSCIEDYSCIVHILQA\n" +
                "MAETGLQPERLLLAGEYASGLERCYLESWIGFERSLGIVLPKTSVTGHFRKAGAAITDWM\n" +
                "RTIWDELKAETDQTVFLEEGKRYVYHTEPTRLTKENSRIRTGGTYLITGGLGGLGYLFAR\n" +
                "HLARNYQANVILTGRSPINEEKKEKMKDLENLGAGVLYAEADVCDPIGMGDCIKRAKERF\n" +
                "GAIHGVIHAAGIESRTSVFENEIGNFRSTLEPKINGSLLLDEWLKNETPDFICYFSSTSA\n" +
                "VLGDFGCCDYAVANRFQMAYANYKNEQSESGNTFVINWPVWKNGGMDVGGEETTGMYLKS\n" +
                "SGQRLLETDEGIELFERIISQDNTQCLVIAGERSRAERFLGIRRDDSSKPDALLETVSRR\n" +
                "IPEESTEKRLEADLKELIHSLLKISKDKLVLHKNWAEFGFDSIYLAKFAALLTSHYGIEV\n" +
                "TPALFYSYATLGDVISYYLTEHKETIETFYRTEETETEAAAPESKEYTDQEIIAMMKQVS\n" +
                "EGTLDFKRVQDIIEGSKTYESMNHKELLDAYRSGTLTIAEVEQKLQAFKRTTAKRPLSEG\n" +
                "QKGLWMLQKMFPEMSAYNIPLCFRFQKLDIETFKNALLSVQRQHPILTSVIKEENGLPYQ\n" +
                "IEDTDRHFPIEEMDLSELSGRDALSFIKEKAKEPFALETGPLLRVQVFRRAKREPIVLIT\n" +
                "IHHIIFDGVSLMTFMSALLDAYAKASEGKEPVMLQQAADYHDFVKWEKELLESAAGKTHL\n" +
                "SYWKKQLEGPLPVLELPSDYPRSSVQTCRGQAYQRLLPDELNRQIKVCAQKHNVNESVVY\n" +
                "LAIFKGLLYQYTNQEDVIVGMPTMGRSEAQFESVIGYFINMIAVRSRETGAKSFTSFLKE\n" +
                "LQLTLAEGLDHAAYPFPALVKELKTERSPAVSPVFQTAFFYQNFFRTEGAEKLAELYQSL\n" +
                "GIEMIEDIHQEGEFELALEVYKKETGTVLQFLYNPDVYSPSFIERMAEHYMKLAEKVLSD\n" +
                "PEIAFEACSGLLNQKRDESRSSHQPNERCIHEVFVEKAGRHPDREAVTFGENSLTYRELD\n" +
                "ERSTALAVYLQEKGVTPECPVGICTERSFEMVIGILAILKAGGAYVPLDPAFPNERMAHV\n" +
                "LTDSGVSIVLTQEKTRGMIEQLAIGGVSTVEIENSGRSVSGAKLTPRSKPHHLAYILYTS\n" +
                "GSTGKPKGVMVEHRAIMNTLQFLEAEYPVAQEDAYLLKTNYVFDVSISELFGWFIGNGRL\n" +
                "VILPPGAEKNPQLCMEYIQTHQVTHLNFAPAVFNVFLETVKRHTAFTEDGPVKYVMVAGE\n" +
                "AFPKDLVKKSVSIFKHARIENIYGPTETSIYAAYYSCGQKEITSRNTPIGKPIHNTRLYI\n" +
                "VDEKLSPVPDGVAGELCVAGAGLARGYYNQPELTAASFIDNPFSEGEKLYKTGDLARWLP\n" +
                "DGNIEYAGRIDSQVKIRGFRIELGAIETKLSEHPDILDQAVVVQEKNGHKKLIAYYTARS\n" +
                "GHTADEKALRNHLLSSLPDYMAPAHFIRLDALPLTPSGKVNRKDLKQRKVIVHRSEKTGR\n" +
                "LPLSEAEAKVTAIWEDLLNTAGIKIEDGFFDVGGDSLLAVAAAERIKQELECDFTVTDLF\n" +
                "EHSTIQAISRFIVETKQAAESEASCQDEREREQTPQNGVPSYFDDSVAIVGISCQFPGAK\n" +
                "NHHEFWKQLREGKESVRFYSEEELREAGVPEDLIENPDYVPALSTIEGKDLFDPEFFHIS\n" +
                "PKDAEFMDPQLRLLLLHSWKAVEDAGYVSKEIPKTSVYMSASNNSYRSLLPEKTTEGHES\n" +
                "PDGYVSWVLAQSGTIPTMVSHKLGLKGPSYFVHSNCSSSLVGLYSAYKSITSGESEYALV\n" +
                "GGATLHAATSIGYVHQNGLNFSSDGHVKAFDASADGMAGGEGAAVILLKKASQAVQDGDH\n" +
                "IYAMLRGIGLNNDGADKVGFYAPSVKGQTDVIQHVLDSTNIHPETISYIEAHGTGTTLGD\n" +
                "PIEMSALQQVYKRYTDREQYCGIGSVKTNIGHLDTAAGLAGCIKVAMSLYHRELAPTINY\n" +
                "TSPNPNIKFSGSPFYVADKRKTLPERETPHRAALSSFGLGGTNAHAIFEQYENKTISGSN\n" +
                "DGQPPYIVPLSARNKQRLTAYASCLSGFLDEAENDVSLHDLAYTYQTGREAMEERAVFIS\n" +
                "HDRHDLNRQLQDFINGNDQNILRGEKVRSREVSAQEMEELAACQTRDEKLKALAALWVEG\n" +
                "ARVDWGLLYPDSAPQRISAPTYPFAEERFWPEETVKQTDTKLLHPLVHQNTSVLQEQRFS\n" +
                "SEFTGKEYFIAEHIIKGMAIVPAAVTLEMARAAAEKSIGGATEESLGLRLKNIVWVRPVI\n" +
                "ADQEAVRVHIGLYEEEDGQIQYRMYGGNDSIGEEAPLYNQGIAEIIRKEPEEAADIEQLK\n" +
                "RRCTQGTIESQAFYKGMIGADYGPGYKGVQLVYKGEDRLLAKLKLPESVSHTKADYILHP\n" +
                "SMMDGALQAAEYLQNVTRALLAESGEPFKAALPFALEELDVLNPCADDMWVHVTFSANNK\n" +
                "AGDPIQKADIDLYDNNGGLCVRMRGFSTRIMEENAGAGVSVSRTDTLLAEPVWKEQPEPA\n" +
                "DHEPSYEEHIIFLCEYDEAVKQAVEAKLEHASVIILDARPASIAERYHSYAGQLFDHIKT\n" +
                "IMKSKPKGRVLFQAVTRSAGLQRVFSGITGLFKTACLEHSKLICQMIEAEEEESAEGIAE\n" +
                "KASENRMHAESVHVKYENGKRFAADWEDMDISQAEPDIPWKDEGVYLITGGAGGLGLIFA\n" +
                "KEIANCTKDAVIILTGRSALREKQKDMLETVRAADASVFYEQTDVTDEAEVYRLIRNIRK\n" +
                "RHGRLDGIVHSAGIIKDNYMVKKTAEEYQHVLAPKVKGLVYLDEASQHEKLDVFIVFSSL\n" +
                "SGVLGSVGQADYASANVFMEMYAEYRRSLQAAGQRYGKTLSVSWPLWKEGGMQAGKQTED\n" +
                "MLMQEAGIAPLGTDAGIKALYQGLMSGTARMTVLEGDVKHMKAKLFRKENDRPEVETGVR\n" +
                "HDIDADSLLEKVKHLLKQQTASLLKVNIDKIDPHEEMTKYGLDSISMTEFTNQLNKTYRL\n" +
                "TLTPTIFFDHPTIHEFAVHLISEYEEEFAGRFAVNTKTVQSARPVKETQITRPAVKRRRT\n" +
                "LPETLPQTVQRGQGPEPIAIVGISGIFPMAEDIEAYWQNLKEGKDCMTEIPKDRWDWRDY\n" +
                "YGDPAKEANKTNVNQGGFIDGIAEFDPLFFGISPREAEQMDPQQRLLLTYAWKAIEDAGY\n" +
                "ASKSLSGTKTGVFIGTGNTGYGSLLANADAEIEGSSAANTSPSVGPNRVSYTLNLHGPSE\n" +
                "PIDTACSSSLVAIHHAVSSIEEGTCDMALAGGINTIVLPDVYISFDKAGALSKEGRCKTF\n" +
                "SDQADGFAHGEGAGLFFLKKLKAAEADGDHIYGVIKGSAVNHGGRAASLTTPNPKQQAEV\n" +
                "IKAAYKKAGIDPKTVSYIEAHGTGTELGDPVEINGLKQAFSSFADGKEKAAGYCGLGSVK\n" +
                "TNIGHLSLAAGAAGIIKILLQMKHRTLVKSLHCETVNPYIQLEDSPFYLVRETMEWKTRT\n" +
                "DERGNEQPRRAGISSFGIGGVNAHVVIEEYIPEDREEADDSHIDPCLFVLSAKNEKRLKE\n" +
                "QAKQLKRALTEKRYDQSSLVSMAYTLQIGRDAMEERLAVIAGSAEELQEKLSQFITGDKH\n" +
                "ADLYRGRIDKGTLQMLTEDEEIQEAVEKWMARGKYAKLLELWVKGLNVDWAKLYGDRPPK\n" +
                "RMSLPSYPFAKDRYWAAKSTGKHEKTSTVSAGKQDALHPLLHRNTSNLAEQRFSSIYTGK\n" +
                "EFYLADHVVKGVPILPGVAHLEMARAAMEQASEVPAGQGSVKLKNTVWVRPITIEDEPVH\n" +
                "VNIRLIPETANDVQFDIYSGRETDQPSVYSQGAVSVRPDAEAPVIDLQKLRSQSAETPFS\n" +
                "ADEVYDMYRKIGFDYGPAFRGVKAIYTGDDFVLGRLSLDAACAGTVQEYVMHPGLMDSAL\n" +
                "QASSILTGTNDEKLMLPFAVQELEVFSACVAEMWVYARLSEDHKAGQIEKRDLDICDENG\n" +
                "KVCVRLKGLSFRMAEKEPEKKEKAPGTLMLEPVWTRSDETATQTEPVFARHIVLLCDTDG\n" +
                "GLKQAVEAAGAECIEMTSQHGKAAARFRDYTGRILETLQKLLKEETDGDVLIQTVLSKTD\n" +
                "KHQLLSGISALLKTAGLEHKKLKTQLIEIEPAENGRITDIIRENKTRADDSHIKYENGIR\n" +
                "YSADVKETAVSGGKIRIPWNDGGIYLITGGAGGLGFIFAKEIARKVKEPTLVLTGRSALS\n" +
                "ENQRMQLQSLESLGAKAEYKQADVTNAQTAADLVKTIETEYGGLHGIIHSAGVMKDQYIA\n" +
                "KKTTEEFYSVLAPKTDGFVNLDEATEHLALDFFIVFSSISGVTGNAGQADYAAANAFMDG\n" +
                "YAAYRNALVTAMYRHGHTLSVNWPLWKNGGMQVNEEMAKLTEKRTGVTPMRTETGIEALY\n" +
                "KAWSTGKTSVLVMEGNRAVMREKLLQKTPASAFAPVKKTGEMPAPKDLTAKLQELLAKEV\n" +
                "SGLLKINIEEIDIELEFNQYGFDSITLTEFANKLNDTYQLDLTPTVFFEYATIQALAHHL\n" +
                "AEDYQTQFAGSTQPKEEKQSGVTDDGGIRLAGNKRFAKTAVQPVQTAAEHKPEPIAIVGM\n" +
                "SGVFPKAANIDEYWRNLEEGKDCITEVPADRWDWREYYGDPLNEANKTNVKWGGFIDGVA\n" +
                "DFDPLFFGISPLEAEQMDPQQRLLMMYAWKAIEDAGYSAKSLSGTKTGLYIGTGNTGYGS\n" +
                "LFSDLDIGGASAANMSPSAGPNRVSYMLNLHGPSEPIDTACSSSLVAIHHAVCAIENGNC\n" +
                "DMAIAGGVNTVVTPQGHIAYDKAGALSKEGKCKTFSDRADGFAVSEGAGILFLKKLSEAE\n" +
                "KAGDHIYGVIKGSAVNHGGRANSLTTPNPKAQAEVVRTAYDKAGIDPRTVTYIEAHGTGT\n" +
                "ELGDPVEINGLKSAFQKLYEKTGDPAVYASHCGLGSAKTNIGHLSLAAGVAGVIKVLMQM\n" +
                "KHKTLAKSLHSEVINPYIKLKDSPFYIVQEKREWTALKDENGNHLPRRAGISSFGIGGVN\n" +
                "AHVVIEEYIPKEERKTAVFTHPQIFVLSAKEEERLQEQAQQLAQASFTDADLTDVAYTLQ\n" +
                "QGRDAMEERAAIIASSAEELRDKLKSCAKGRYDIAGIYKGKAGKTSLKSILAGANGEADI\n" +
                "EELISRRENDKLAELWVQGADIKWDGLYSDIKPQRLSLPAYPFAKERYWITDNRPKAEKP\n" +
                "QAVPTSRVLHPLLHENVSDLTEQRYRSEFTGQETIFTDHLIKGKPVMPGVAYLEMARAAV\n" +
                "AQAVKGQKERPSVTRLKNIVWVRPIEAGNRPIEAQISLNPRENGEIVYDVYTNSQTEASG\n" +
                "RQIHCQGAAGILSAGEAPHRDIGALKAQCGLSILTSEQCYGLFSKIGIDYGPGQQGIQQI\n" +
                "HIGSNQALAELRLPSFLEETADQYVLHPCMLDSALQATIGLKLHADDNQLSLPFALEELD\n" +
                "IFSPCTTSMWAYVSSRGTDEKIQRMDIDLCDETGRVCVRIKGISSRMMEGPAPETSLNGA\n" +
                "NLLAPVWDLAEFRDQSPAYKTEEVVFIAGDEESAAFQLHHPSAKRLHITPEDEIEAVAAE\n" +
                "LKATGSFGHIVWIAPFHSADDMVKAQDAGVIQMYRVIKAMLALGYGGKRISLTAVTIKTQ\n" +
                "SVQPADIIDPAHAGIHGLVGSLAKEYPNWQTRLIDAGCPEDVSKAELFSAPFDEQGNTWA\n" +
                "YRNNHWYKQRLIPVQQPVSSRPAYQKGGVYVVIGGAGGIGEAWSEYAVKTYQARVVWIGR\n" +
                "RKHNSAIQEKIDRLSQFGPAPIYIEADAANPNELTRAYETIKRTHPQINGIIHSAIVLED\n" +
                "QSLANMPESRLKSVLAAKVNVSVNMARVFRNEPLDFALFFSSVQSFARAAGQSNYAAGCS\n" +
                "FKDAFAAHLAQVRPYSAAVMNWSYWGSVGIVSSADYQERMKQAGVGSIEAPEAMAALERL\n" +
                "LGGPLNQFVMMKQAEEPEEKPEEMIEVYPEHHGSAMQKLRSYQPKVTRHVQQLSVKEGTA\n" +
                "LQNTEDLLYKLLAGQLKSVGFFTENETQPVMQGFYGRWLEESISILVQKGFLKQSGSTYV\n" +
                "LTDPIERADVLWQEWDEKKAPLLKDSSKQAMITLVETALRALPDILSGRVSATDVLFPDS\n" +
                "SMELVEGIYKNNETADYFNEVLADTLTAFIEERLKEDPNAEIRILEIGAGTGGTSAAVFK\n" +
                "RLKEYKHHVKEYCYTDLSKAFFMHAEKKYGPDNPYLTYKRFNVEEPPALQGIEAGAYDAV\n" +
                "IAANVLHATKNIRRTLRNAKAVLKKNGILLLNEISSHSVYSHLTFGLLEGWWLYEDAKLR\n" +
                "IPGCPGLYPEAWQSALESEGYRYVTFMAESSHHLGQQIVAAESDGVIRQKQPDAQAVEET\n" +
                "AASKEPADFTEPSFSVTDRTVQFIKETLAKSIKLAPERIQPETSFEKYGIDSILQVNFIR\n" +
                "ELETLTGELPKTVLFEHTNTKELAEYLLENYPDKLQQAFGAEQVPPETEHPEPAMNEPVP\n" +
                "LVTETRRFITEPKAPKPETETVTVNRSDRDDIAIIGISGRYPESETLDELWEHLKAGDSC\n" +
                "ITEAPENRWKSGLLKTMAKETRKEERKTRYGGFLQHIDAFDHHLFDIREDHVMEMTPELR\n" +
                "LSLETVWETFENGGYSLERVTEWQESDSGIGVFMGSMYNQYFWNIPSLEKAALSSNGGDW\n" +
                "HIANRISHFFNLTGPSMGVTTACSSSLSAIHLACESLKLNSCSMAIAGGVNLTLEPSKYD\n" +
                "ALERANLLEQGSESKSFGTGTGLMPGEGVGAVLLKPLSKALADKDHIYGVIKSSALCHSG\n" +
                "GRQMYTAPDPKQQAKLMAASIDKAGINPETISYVESAANGSVLGDPIEVIALTNAFAQYT\n" +
                "DKKRFCALGSVKSNLGHLEAASGMSQLAKVLLQMERETLVPTINAKPQNPNINLEQTAFY\n" +
                "LQEKTEYWERMRDAETGDIIPRRSMINSFGAGGAYANLIVEEYISPNSDQARHGDEEYIF\n" +
                "PVSAKTKWSFEAYLDRLTAFLEKTPPLHPAAIASALQKRTHHSKYRAAFTAASVQELLEK\n" +
                "LAAYRMDQRNLNFSESDIGRRARQWEKGENIAFDQLQQEHAVHLPAYAFDHGTSFQFGES\n" +
                "ENAAGVQAVYSDDDPYVKGHQFSGEPVLVGATYNSLAVDHFCDLFPEAEGGQIKKLNYAS\n" +
                "PITVKKGDRIELKTESKQNGDGFELSIMHRSRTSPDWSIAAYAECSPYPFQKQHADLAAI\n" +
                "QRSYREVGRIDELYGDGTGTVVWGEEFKTITRLYKGSDAVLAKVNLNNSDSQQAHHYAVN\n" +
                "PLIANSAYLASLSLLDQTEAESYLPFGINSVTFSSPEDLTDCWLHIKLAKQTGEMILINA\n" +
                "DVISRRSEVVMRFEGYALKRFRPKTEQMNQPARTAVKNAGAPISAGSLTDDIRSYVLGKL\n" +
                "AKTMDEPAPSLRSDANIMELGLDSVSLIGLTKEIGQEADIDVNPTLFFEYPTAEELTRHF\n" +
                "ASAYESKFSQLLADHKHSEEARVTETEERTLPRKQHPPCDNADVKQGIAIIGMSAQFPQS\n" +
                "PDIQSFWEHIVNGDHCITEIPADRWDWRRYAGDENDTSLRWGGFIDGVGEFDPLFFGISP\n" +
                "KEASQMGPEQFLLLMHTWKAMEDAGLTNKALSSRPTGVFVAAGNSDPNNGTAIPSIIPNR\n" +
                "ISYALNLQGPSEYYEAACTSTLVALHRAVQSIRHNECEQAVVGAANILQSPKGFIGFDSM\n" +
                "GYLSKNGRAKSFQKDADGFVRSEGAGVIIIKPLEAAIEDGDHIHMVIKGTGVSHGGKGMS\n" +
                "LHAPNPAGMKAAMKKAYEDTDVDPQTVTYIEAHGIASEMADALEFNAIKAGYGESANQEE\n" +
                "SAPCYISTVKPCIGHGELASGLAALIKVAMAMKHHTIPGIPRFTAANEQMAIQKSRFRFT\n" +
                "EDNQEWTQLTDHTGRPIPRRAAINSYGFGGMNAHVVLEQYSSSHKDKESVHEPQLIVLSA\n" +
                "KSEGRLKAAAGQLADFVQTGDTPSLRDIAYTLQTGREAMNGRLALVARNQDELLEKLKEY\n" +
                "RAFSEESNGMKSFFTGSQQTGSGDIGILLEGTLGTVVTETLLAENNLEKLAFCWVKGADI\n" +
                "PWDRLHQGKSVKRVPLPTYPFENHKYWKGGQPEDISLAPVSQDPQLCRESAADIVADILG\n" +
                "MKAAEIDQNKPLTEYGFDSISSIQLLKKLEDGDSRISLEALQKCSTLQEIGMLLKTNQPQ\n" +
                "ETGRNFPELVKLNEREKGRPVFWFHGGTGGVEAYQPFAKKSQRPFYGIQARGLTGKEPLQ\n" +
                "GIEETAASYKRIIQAVQPKGPYDLGGYSLGGMLAYETARLLQEEGHTVKSAVMIDTPYSE\n" +
                "KWKERKPSVKSVMLQTINTMLTAYLKPENLEEALISREDITVQAEEEEVLKELIGLAKKR\n" +
                "GLPKSEEAIRMQLEQMMKTQLAYGMEEYDMKPLPHPEALQCYYFRNKSGLFLGDLERYLT\n" +
                "AEEEQIPLDHDAYWKEWEHQMKQFHLLDVHSSNHVTMLSEPKPQNAIKAFCEKLYANKGT\n" +
                "ISANFLKSFRKKLDETNELVKR");
            $('#input-form').submit();
        }
    </script>

</head>
<body>
<!--[if lt IE 7]>
<p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade
    your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to
    improve your experience.</p>
<![endif]-->

<h1 class="textCentering"><i>trans</i>ATor web application</h1>

<p class="textCentering">
    The <i>trans</i>-AT polyketide synthase predictor (<i>trans</i>ATor) is a genome mining tool that predicts the core
    structure of a
    <i>trans</i>-AT PKS derived polyketide based on the protein sequence of the corresponding biosynthetic gene cluster.
    For more information on <i>trans</i>ATor see below.
    Use protein sequences in proper fasta format as input.
</p>
<form id="input-form" action="ValidateInput" method="post" enctype="multipart/form-data">
    <p class="textCentering">Paste your protein sequence(s) or individual KS domains in proper FASTA format, or
        use the bacillaene PKS as an <a href="javascript:void(0)" onclick="submitExample()">example</a></p>
    <div class="content" style="vertical-align: middle;">
        <div class="textarea textCentering">
            <textarea rows="10" cols="50" name="sequenceInput" id="sequenceInput"
                      style="color: #9b9b9b; text-align: left"></textarea>
        </div>
        <p class="textCentering">Or alternatively:</p>
        <div class="textarea-instruction textCentering">
            <p class="textCentering">Upload protein sequences in FASTA format.
            </p>
        </div>
        <br>
    </div>
    <div class="textCentering">
        <input type="file" name="fastaFile" value="Choose fasta"/>
    </div>

    <div class="textCentering">
        <input class="submitButton" type="submit" value="Submit"
               onclick="document.getElementById('loading').style.display = 'block';" style="margin-top: 2em"/>
    </div>

</form>

<p class="textCentering">
    <a href="https://github.com/PielLab/transator-wiki/wiki#about-transator">About transATor</a>
    <a href="https://github.com/PielLab/transator-wiki/wiki#tutorial">Tutorial</a>
    <a href="https://github.com/PielLab/transator-wiki/wiki#faqs">FAQs</a>
</p>


<script>window.jQuery || document.write('<script src="js/vendor/jquery-1.9.1.min.js"><\/script>')</script>
<script src="js/plugins.js"></script>
<script src="js/main.js"></script>

</body>
</html>
